# .github/workflows/sql-check-manual-trigger.yml
name: Manual SQL Script Trigger

on:
  workflow_dispatch:
    inputs:
      script_id:
        description: "The ID of the SQL script to run (from manifest.json)"
        required: true
        type: string

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }} # Make sure MONGODB_URI is also a secret
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed if run_sql needs it, otherwise optional

jobs:
  run-manual-sql-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env.local
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.local
          # Pass the GitHub Run ID for potential linking in saved results
          echo "GITHUB_RUN_ID=${{ github.run_id }}" >> .env.local 
          echo "GITHUB_SERVER_URL=${{ github.server_url }}" >> .env.local
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env.local
          echo "NODE_ENV=production" >> .env.local
          echo "--- .env.local content (for manual trigger) ---"
          cat .env.local || echo ".env.local not found or empty"
          echo "--- .env.local content end ---"

      - name: Run SQL Check Script
        env:
          DOTENV_CONFIG_PATH: .env.local
        run: |
          echo "Current working directory: $(pwd)"
          echo "Using .env file: ${DOTENV_CONFIG_PATH}"
          echo "Script ID to execute: ${{ github.event.inputs.script_id }}"
          ls -la ${DOTENV_CONFIG_PATH}
          echo "About to execute ts-node..."
          # Use ts-node with -r to preload dotenv/config, using the input script_id
          npx ts-node -r dotenv/config scripts/run-sql.ts "${{ github.event.inputs.script_id }}"
        continue-on-error: false # Fail the workflow if the script fails
