name: SQL Script Cron Job

on:
  schedule:
    - cron: "0 8 * * *"  # UTC 8:00 = 芝加哥夏令时凌晨 3:00 CDT
  workflow_dispatch: 
    inputs:
      execution_mode:
        description: "执行模式 (all: 所有脚本, scheduled: 仅定时脚本)"
        required: false
        default: "scheduled"
        type: choice
        options:
          - scheduled
          - all
      debug_mode:
        description: "调试模式"
        required: false
        default: false
        type: boolean

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  run-sql-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env.local
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.local
          echo "NODE_ENV=production" >> .env.local

      - name: Debug environment setup
        run: |
          pwd
          ls -la
          echo "--- .env.local content start ---"
          cat .env.local || echo ".env.local not found or empty"
          echo "--- .env.local content end ---"
          echo "NODE_ENV: $NODE_ENV"
          echo "GitHub Run ID: $GITHUB_RUN_ID"
          echo "Execution Mode: ${{ github.event.inputs.execution_mode || 'scheduled' }}"
          echo "Debug Mode: ${{ github.event.inputs.debug_mode || 'false' }}"
          
          # 时区和时间调试
          echo "--- 时间和时区信息 ---"
          echo "UTC 时间: $(date -u)"
          echo "当前时区时间: $(date)"
          echo "TZ环境变量: $TZ"
          echo "系统时区: $(timedatectl show --property=Timezone --value 2>/dev/null || cat /etc/timezone 2>/dev/null || echo 'Unknown')"
          
          # 触发方式检查
          echo "--- 触发方式分析 ---"
          echo "GitHub Event Name: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "✅ 由定时任务触发"
            echo "预期下次运行: 明天 UTC 8:00 ($(date -d 'tomorrow 08:00 UTC' '+%Y-%m-%d %H:%M:%S %Z'))"
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "✅ 由手动触发"
          else
            echo "⚠️  由其他事件触发: ${{ github.event_name }}"
          fi
          
          # 环境变量检查
          echo "--- 必需环境变量检查 ---"
          if [ -n "$DATABASE_URL" ]; then
            echo "✅ DATABASE_URL: 已设置 (长度: ${#DATABASE_URL})"
          else
            echo "❌ DATABASE_URL: 未设置"
          fi
          
          if [ -n "$MONGODB_URI" ]; then
            echo "✅ MONGODB_URI: 已设置 (长度: ${#MONGODB_URI})"
          else
            echo "❌ MONGODB_URI: 未设置"
          fi
          
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            echo "✅ SLACK_WEBHOOK_URL: 已设置 (长度: ${#SLACK_WEBHOOK_URL})"
          else
            echo "⚠️  SLACK_WEBHOOK_URL: 未设置 (通知功能将跳过)"
          fi

      - name: Run SQL Scripts from MongoDB
        env:
          DOTENV_CONFIG_PATH: .env.local
          GITHUB_RUN_ID: ${{ github.run_id }}
          EXECUTION_MODE: ${{ github.event.inputs.execution_mode || 'scheduled' }}
        run: |
          echo "Current working directory: $(pwd)"
          echo "Using .env file: ${DOTENV_CONFIG_PATH}"
          echo "GitHub Run ID: ${GITHUB_RUN_ID}"
          echo "执行模式: ${EXECUTION_MODE}"
          echo "定时执行时间: 芝加哥夏令时凌晨 3:00 (UTC 8:00)"
          ls -la ${DOTENV_CONFIG_PATH}
          echo "开始从MongoDB批量执行SQL脚本（所有可用脚本）..."
          # 使用新的批量执行脚本，scheduled模式现在执行所有脚本
          npx ts-node -r dotenv/config scripts/run-all-scripts.ts ${EXECUTION_MODE}
        continue-on-error: false
